[package]
name = "abc257"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = { version = "0.3.8", features = ["derive"] }
superslice = { version = "1.0.0" }
num-bigint = "=0.2.6"
num-traits = "=0.2.11"

[profile.release]
lto = true
panic = 'abort'
