[package]
name = "abc178"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = { version = "0.3.8", features = ["derive"] }
itertools = "0.9.0"

[profile.release]
lto = true
panic = 'abort'
